version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
platform: x64
clone_depth: 1
init:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
environment:
  VULKAN_SDK: c:\VulkanSDK\1.2.176.1
install:
- cmd: >-
    if not exist VulkanSDK_1.2.176.exe curl -L --silent --show-error --output VulkanSDK.exe https://www.dropbox.com/s/hhk3brlral121kn/VulkanSDK.exe?dl=1

    VulkanSDK_1.2.176.exe /S

cache: VulkanSDK_1.2.176.exe
build_script:
- ps: >-
    git submodule init

    git submodule update --depth=1

    & "c:\projects\island\scripts\ci\run_tests.ps1"
